/* ============================================================
   ENERGY STORAGE SYSTEM TESTING — QUESTION BANK (English)
   ============================================================
   HOW TO UPDATE THE BANK:
   - Edit THIS file (quiz-en.js), save, then reopen exam-en.html.
   - You do NOT need to touch exam-en.html.
   -
   - Each question is an object. Three types are supported:
   -
   -   single:    { id, chapter, type:'single', q, opts:[...], ans:'B', exp }
   -   truefalse: { id, chapter, type:'truefalse', q, ans:true, exp }
   -   multi:     { id, chapter, type:'multi', q, opts:[...], ans:['A','C'], exp }
   -
   - - ans letters map to opts order: A = 1st option, B = 2nd, ...
   - - truefalse has NO opts (True/False shown automatically); ans is true or false.
   - - chapter must match one of the CHAPTERS ids below.
   ============================================================ */

const CHAPTERS = [
  { id: 1, title: "Energy Storage System Testing" },
  { id: 2, title: "RTE Data Analysis" }
];

const QUESTIONS = [
  { id:"Q01", chapter:1, type:"single",
    q:"According to DL/T 1194-2012, a BESS consists of a storage battery and a _____.",
    opts:["supercapacitor","shunt voltage-type converter","flywheel","uninterruptible power supply (UPS)"],
    ans:"B",
    exp:"A BESS is an energy storage system consisting of a battery and a shunt (parallel) voltage-type converter (DL/T 1194-2012, 6.22)." },

  { id:"Q02", chapter:1, type:"single",
    q:"The first-level pipeline of the liquid-cooling system adopts which scheme?",
    opts:["top-in bottom-out","bottom-in bottom-out","top-in top-out","side-in side-out"],
    ans:"B",
    exp:"The first-level pipeline uses a 'bottom-in bottom-out' scheme to ensure uniform PACK flow; pipes are wrapped with insulation foam to prevent condensation." },

  { id:"Q03", chapter:1, type:"single",
    q:"The fire suppression system of an electrochemical storage cabin consists of how many main parts?",
    opts:["two","three","four","five"],
    ans:"C",
    exp:"Four parts: fire main engine; cabin-level combustible detector / smoke / temperature sensors; sound-light alarm + intake/exhaust system; water spray system." },

  { id:"Q04", chapter:1, type:"single",
    q:"What is the main function of the Local Controller (LC)?",
    opts:["AC/DC power conversion","monitor local device status and execute strategy-based actions, plus record data","accept external grid dispatch","acquire cell temperature only"],
    ans:"B",
    exp:"The LC monitors local device status, performs actions according to strategy, and records data." },

  { id:"Q05", chapter:1, type:"truefalse",
    q:"A DC cabin integrates the PCS inside the cabin.",
    ans:false,
    exp:"False. A DC cabin has the PCS external; an AC cabin integrates the PCS (and an optional transformer) inside." },

  { id:"Q06", chapter:1, type:"truefalse",
    q:"An AC cabin can independently realize energy storage, conversion and release.",
    ans:true,
    exp:"True. An AC cabin integrates the battery array, BMS, auxiliary systems, PCS and an optional transformer, so it can independently store/convert/release energy." },

  { id:"Q07", chapter:1, type:"truefalse",
    q:"The EMS is responsible for charge/discharge control and accepts external dispatch.",
    ans:true,
    exp:"True. The EMS handles system charge/discharge control, accepts external scheduling, and interacts with local controllers." },

  { id:"Q08", chapter:1, type:"multi",
    q:"Which of the following are typical components of a battery cabin?",
    opts:["Cells / modules / racks","BMS and high-voltage box (BDU)","Distribution cabinet and bus cabinet","Liquid cooling / air conditioner and fire protection system"],
    ans:["A","B","C","D"],
    exp:"A battery cabin contains modules, AC, battery racks/wiring, fire protection, BDU, racks, cells, BMS, cooling machine, and distribution/bus cabinets." },
  { id:"Q09", chapter:1, type:"single",
    q:"In the BMS three-level architecture, which level acquires Pack cell voltage/current/temperature and performs thermal management and passive balancing?",
    opts:["BAU","BCU","BMU","PCS"],
    ans:"C",
    exp:"BMU acquires Pack cell data and provides thermal management and passive balancing." },

  { id:"Q10", chapter:1, type:"single",
    q:"What is the BCU voltage acquisition range?",
    opts:["0–50V","9–32V","50V–1500V","0–1500V"],
    ans:"C",
    exp:"BCU voltage acquisition is 50V–1500V (±0.5%); 9–32V is its working voltage — do not confuse them." },

  { id:"Q11", chapter:1, type:"single",
    q:"When severe over-voltage, under-voltage, over-current (short circuit) or leakage (insulation) occurs, which level controls the cluster breaking?",
    opts:["BMU","BCU","BAU","EMS"],
    ans:"B",
    exp:"The BCU controls the breaking of the battery cluster under such abnormal faults." },

  { id:"Q12", chapter:1, type:"single",
    q:"Which level performs numerical calculation, performance analysis and alarm processing on data uploaded by BMU and BCU?",
    opts:["BMU","BCU","BAU","PCS"],
    ans:"C",
    exp:"The BAU performs calculation / analysis / alarm / record storage and linkage control with PCS and EMS." },

  { id:"Q13", chapter:1, type:"single",
    q:"What is the BMU balancing current?",
    opts:["10mA","50mA","100mA","500mA"],
    ans:"C",
    exp:"The BMU uses passive balancing with a current of 100mA." },

  { id:"Q14", chapter:1, type:"single",
    q:"How many cells does a BMU manage?",
    opts:["24","36","52","100"],
    ans:"C",
    exp:"A BMU manages 52 cells (voltage balancing range 0–5V, passive balancing current 100mA)." },

  { id:"Q15", chapter:1, type:"truefalse",
    q:"The BMU uses active balancing.",
    ans:false,
    exp:"False. The BMU uses passive balancing (100mA)." },

  { id:"Q16", chapter:1, type:"truefalse",
    q:"The BCU controls cluster breaking when serious over-voltage, under-voltage, over-current or leakage occurs.",
    ans:true,
    exp:"True." },

  { id:"Q17", chapter:1, type:"truefalse",
    q:"The BAU performs linkage control with PCS and EMS.",
    ans:true,
    exp:"True. The BAU links with PCS, EMS, etc." },
  { id:"Q18", chapter:1, type:"single",
    q:"What is the core power device inside the PCS for AC/DC conversion?",
    opts:["IGBT","relay","fuse","contactor"],
    ans:"A",
    exp:"The IGBT is the core power switching device implementing AC/DC conversion inside the PCS." },

  { id:"Q19", chapter:1, type:"single",
    q:"A liquid-cooled cabin has a rated energy of 3354 kWh. At the 0.5P rate, what is the maximum operating power?",
    opts:["838.5 kW","1677 kW","3354 kW","6717 kW"],
    ans:"B",
    exp:"0.5P = 3354 × 0.5 = 1677 kW." },

  { id:"Q20", chapter:1, type:"single",
    q:"A 1P rate means the system can fully discharge the rated energy in _____.",
    opts:["0.5 hour","1 hour","2 hours","4 hours"],
    ans:"B",
    exp:"1P means fully discharging the rated energy in 1 hour; 0.5P takes 2 hours." },

  { id:"Q21", chapter:1, type:"single",
    q:"What is the purpose of anti-islanding protection?",
    opts:["improve efficiency","stop feeding power to the grid when the grid is down","balance cells","limit charge current"],
    ans:"B",
    exp:"Anti-islanding protection makes the PCS stop feeding the grid when it is de-energized, protecting maintenance personnel." },

  { id:"Q22", chapter:1, type:"truefalse",
    q:"The PCS can regulate both active and reactive power.",
    ans:true,
    exp:"True. The PCS can rapidly regulate active and reactive power exchange with the AC system." },

  { id:"Q23", chapter:1, type:"truefalse",
    q:"In off-grid mode, the PCS uses V/f control to maintain voltage amplitude and frequency.",
    ans:true,
    exp:"True. Off-grid V/f control keeps voltage amplitude (V) and frequency (F) constant." },

  { id:"Q24", chapter:1, type:"multi",
    q:"Which of the following are PCS control functions?",
    opts:["Grid-connected constant-power charge/discharge","Grid-connected constant voltage","Current-limiting charge","Off-grid V/f control","Reactive power regulation"],
    ans:["A","B","C","D","E"],
    exp:"All are PCS control functions (anti-islanding protection is also listed under control in the course)." },

  { id:"Q25", chapter:1, type:"multi",
    q:"Which of the following are PCS protection functions?",
    opts:["Battery polarity reverse protection","DC over-voltage/over-current protection","Grid over/under-voltage protection","Grid over/under-frequency protection","IGBT module over-current/over-temperature protection"],
    ans:["A","B","C","D","E"],
    exp:"All are PCS protection functions (plus grid over-current protection)." },
  { id:"Q26", chapter:1, type:"single",
    q:"The insulation resistance test is based on which law?",
    opts:["Kirchhoff's law","Ohm's law","Joule's law","Lenz's law"],
    ans:"B",
    exp:"Apply a voltage → measure current → calculate R = U/I using Ohm's law." },

  { id:"Q27", chapter:1, type:"single",
    q:"In a withstand voltage test, pass/fail is judged by _____.",
    opts:["the insulation resistance value","comparing leakage current with a judgment current","the ground resistance","the temperature rise"],
    ans:"B",
    exp:"If leakage current < judgment value → pass; if greater → cut off the voltage and alarm (breakdown)." },

  { id:"Q28", chapter:1, type:"single",
    q:"What does the ground continuity test mainly measure?",
    opts:["insulation resistance","leakage current","ground resistance","contact voltage"],
    ans:"C",
    exp:"Inject a current, measure voltage/current, and calculate the ground resistance; criterion is an upper limit." },

  { id:"Q29", chapter:1, type:"single",
    q:"What is the maximum current of the short-circuit test machine?",
    opts:["1200 A","6000 A","12000 A","200 kN"],
    ans:"C",
    exp:"Short-circuit tester: 0–100 mΩ, 0–12000 A. 200 kN is the pressure of the needling/extrusion tester." },

  { id:"Q30", chapter:1, type:"single",
    q:"What is the pressure range of the needling/extrusion test machine?",
    opts:["0–100 kN","0–200 kN","0–1000 kN","0–12000 A"],
    ans:"B",
    exp:"Needling/extrusion tester: speed 0.05–100 mm/s, pressure 0–200 kN." },

  { id:"Q31", chapter:1, type:"truefalse",
    q:"In a withstand voltage test, if the leakage current is greater than the judgment current, the device passes.",
    ans:false,
    exp:"False. It fails — the test voltage is cut off and a sound-light alarm is issued." },

  { id:"Q32", chapter:1, type:"truefalse",
    q:"Insulation resistance is calculated by applying a voltage, measuring the resulting current, and using Ohm's law.",
    ans:true,
    exp:"True." },

  { id:"Q33", chapter:1, type:"truefalse",
    q:"The pass criterion of the ground continuity test is a resistance upper limit (the lower the ground resistance, the better).",
    ans:true,
    exp:"True. A lower ground resistance means fault current can be safely discharged." },

  { id:"Q34", chapter:1, type:"multi",
    q:"Which of the following are the three electrical safety (dielectric) tests?",
    opts:["Insulation resistance test","Withstand voltage test","Ground continuity test","Vibration test","Drop test"],
    ans:["A","B","C"],
    exp:"The three safety tests are insulation resistance, withstand voltage and ground continuity; vibration/drop are mechanical safety tests." },
  { id:"Q35", chapter:1, type:"single",
    q:"The V-model evolved from which development model?",
    opts:["Waterfall model","Rapid Application Development (RAD) model","Spiral model","Agile model"],
    ans:"B",
    exp:"The V-model evolved from the RAD (Rapid Application Development) model." },

  { id:"Q36", chapter:1, type:"single",
    q:"In performance testing, at least how many full charge/discharge cycles must be performed using the PCS?",
    opts:["1","2","3","5"],
    ans:"C",
    exp:"At least 3 complete charge/discharge cycles are required." },

  { id:"Q37", chapter:1, type:"single",
    q:"The Japanese 'Fire Service Hazard 303' standard corresponds to which test?",
    opts:["vibration test","3-meter drop test","needling test","fire test"],
    ans:"B",
    exp:"Japanese 'Fire Service Hazard 303' corresponds to a 3-meter drop test." },

  { id:"Q38", chapter:1, type:"truefalse",
    q:"Energy storage system tests can be classified by test object, test type and test stage.",
    ans:true,
    exp:"True — three classification dimensions." },

  { id:"Q39", chapter:1, type:"truefalse",
    q:"The right side of the V-model includes unit, integration, system and acceptance testing.",
    ans:true,
    exp:"True." },

  { id:"Q40", chapter:1, type:"multi",
    q:"Which of the following are cell-level electrical safety tests?",
    opts:["Overcharge","Overdischarge","Short circuit","Thermal runaway","Heating"],
    ans:["A","B","C","D"],
    exp:"Cell electrical safety: overcharge, overdischarge, short circuit, thermal runaway. Heating is an environmental safety test." },

  { id:"Q41", chapter:1, type:"multi",
    q:"Which of the following are cell-level mechanical safety tests?",
    opts:["Vibration","Drop","Extrusion","Needling","Heating"],
    ans:["A","B","C","D"],
    exp:"Cell mechanical safety: vibration, drop, extrusion, needling. Heating is environmental." },

  { id:"Q42", chapter:1, type:"multi",
    q:"Which of the following are typical DI (digital input) signals?",
    opts:["AC power-on","Mains switch closed","Door access","Emergency stop","Fire alarm"],
    ans:["A","B","C","D","E"],
    exp:"DI includes AC power-on, mains switch, door access, ATS signal, isolation switch, fuse, SPD, water immersion, emergency stop, fire, etc." },

  { id:"Q43", chapter:1, type:"multi",
    q:"Which of the following are typical DO (digital output) signals?",
    opts:["DC power-on","DC fault","Total power cut-off","Stop BMS","Stop PCS"],
    ans:["A","B","C","D","E"],
    exp:"DO includes DC power-on, DC fault, total power cut-off, UPS cut-off, stop BMS, stop PCS, etc." },
  { id:"Q44", chapter:1, type:"single",
    q:"Which standard is the evaluation method for thermal runaway fire spread in battery energy storage systems?",
    opts:["UL 1973","UL 9540","UL 9540A","UL 1642"],
    ans:"C",
    exp:"UL 9540A evaluates thermal runaway fire spread (UL 9540 is the system safety standard)." },

  { id:"Q45", chapter:1, type:"single",
    q:"What is the maximum DC voltage covered by IEC 63056?",
    opts:["1000 V","1200 V","1500 V","3000 V"],
    ans:"C",
    exp:"IEC 63056 applies to secondary lithium batteries for power storage with a maximum DC voltage of 1500 V." },

  { id:"Q46", chapter:1, type:"single",
    q:"GB/T 36276 is a national standard for which market?",
    opts:["EU","Japan","North America","China"],
    ans:"D",
    exp:"GB/T 36276 is the Chinese national standard test for energy storage batteries." },

  { id:"Q47", chapter:1, type:"truefalse",
    q:"UL 9540 is the world's first safety standard for energy storage systems.",
    ans:true,
    exp:"True." },

  { id:"Q48", chapter:1, type:"truefalse",
    q:"UN38.3 is the international transport safety test standard for secondary lithium batteries.",
    ans:true,
    exp:"True." },

  { id:"Q49", chapter:1, type:"multi",
    q:"Energy storage certification is mainly divided into which markets?",
    opts:["CN (China)","JP (Japan)","NA (North America)","EU (Europe)"],
    ans:["A","B","C","D"],
    exp:"Four markets: CN, JP, NA, EU." },

  { id:"Q50", chapter:1, type:"multi",
    q:"Which of the following are common North American (NA) energy storage certification standards?",
    opts:["UL 1973","UL 9540","UL 9540A","UL 1642","IEC 62619"],
    ans:["A","B","C","D"],
    exp:"NA uses UL 1973 / 9540 / 9540A / 1642; IEC 62619 belongs to EU." }
,

  /* ---------- Chapter 2: RTE Data Analysis ---------- */
  { id:"Q51", chapter:2, type:"single",
    q:"RTE (Round Trip Efficiency) is defined as ____.",
    opts:["discharge energy ÷ charge energy", "charge energy ÷ discharge energy", "discharge power ÷ charge power", "charge energy × discharge energy"],
    ans:"A",
    exp:"RTE = discharge energy ÷ charge energy, measured over a full charge–full discharge cycle." },
  { id:"Q52", chapter:2, type:"single",
    q:"RTE must be measured under a _____ condition.",
    opts:["full charge and full discharge cycle", "charge to 100% and discharge to 50%", "partial charge only", "constant-voltage only"],
    ans:"A",
    exp:"RTE requires a full 0%↔100% charge–discharge cycle." },
  { id:"Q53", chapter:2, type:"single",
    q:"On site, the battery typically starts at about what SOC before the RTE test?",
    opts:["10%", "30%", "50%", "80%"],
    ans:"B",
    exp:"Site batteries usually start around SOC 30%." },
  { id:"Q54", chapter:2, type:"single",
    q:"During full charge at constant power, the current is reduced to 0.1P at cell voltage ____.",
    opts:["3.0V", "3.2V", "3.6V", "3.62V"],
    ans:"C",
    exp:"At cell 3.6V the current is stepped down to 0.1P; charging then continues to 3.62V." },
  { id:"Q55", chapter:2, type:"single",
    q:"Full charge calibrates SOC to 100% at cell voltage ____.",
    opts:["3.6V", "3.62V", "2.8V", "2.9V"],
    ans:"B",
    exp:"At cell 3.62V, SOC is calibrated to 100%." },
  { id:"Q56", chapter:2, type:"single",
    q:"During full discharge, the cutoff cell voltage (SOC = 0) is ____.",
    opts:["2.8V", "2.9V", "3.0V", "3.6V"],
    ans:"A",
    exp:"Full discharge ends at cell 2.8V, calibrated to SOC = 0%." },
  { id:"Q57", chapter:2, type:"single",
    q:"Before looking up the OCV-SOC table, the cell must rest for at least ____.",
    opts:["10 minutes", "30 minutes", "1 hour", "2 hours"],
    ans:"D",
    exp:"OCV lookup requires a rest of at least 2 hours for the voltage to stabilize." },
  { id:"Q58", chapter:2, type:"single",
    q:"What is the standard testing temperature for RTE?",
    opts:["20℃", "25℃", "30℃", "22℃"],
    ans:"B",
    exp:"The standard test temperature is 25℃." },
  { id:"Q59", chapter:2, type:"single",
    q:"Which range is the suitable temperature window for RTE testing?",
    opts:["0–10℃", "15–35℃", "40–60℃", "-10–0℃"],
    ans:"B",
    exp:"The suitable range is 15–35℃ (customers often specify 22–28℃)." },
  { id:"Q60", chapter:2, type:"single",
    q:"A cell-to-cell voltage difference greater than ____ is considered abnormal and requires balancing.",
    opts:["10 mV", "50 mV", "100 mV", "500 mV"],
    ans:"C",
    exp:"A voltage difference > 100 mV is abnormal; balancing is required." },
  { id:"Q61", chapter:2, type:"single",
    q:"How does the charge/discharge rate affect the released energy?",
    opts:["Higher current releases more energy", "Higher current releases less energy", "Current has no effect", "Lower current releases less energy"],
    ans:"B",
    exp:"Higher current (e.g. 1P) releases less energy; lower current releases more." },
  { id:"Q62", chapter:2, type:"single",
    q:"In this course the cell is LFP with nominal voltage / capacity ____.",
    opts:["3.0V / 200Ah", "3.2V / 280Ah", "3.7V / 280Ah", "3.2V / 100Ah"],
    ans:"B",
    exp:"LFP cell, nominal 3.2V / 280Ah." },
  { id:"Q63", chapter:2, type:"single",
    q:"One PACK consists of how many cells in series?",
    opts:["12", "24", "48", "52"],
    ans:"D",
    exp:"A PACK = 52 cells in series." },
  { id:"Q64", chapter:2, type:"single",
    q:"Which formula gives the nominal total energy?",
    opts:["cell V × cell Ah × cells/PACK × PACKs/RACK × RACKs", "cell V × cell Ah only", "cell Ah × RACKs", "cell V × PACKs"],
    ans:"A",
    exp:"Nominal total energy = cell V × cell Ah × cells/PACK × PACKs/RACK × RACKs." },
  { id:"Q65", chapter:2, type:"single",
    q:"Using 3.2V × 280Ah × 52 × 8 × 10, the nominal total energy is about ____.",
    opts:["~2000 kWh", "~3700 kWh", "~5000 kWh", "~1000 kWh"],
    ans:"B",
    exp:"≈ 3727 kWh (about 3700 kWh)." },
  { id:"Q66", chapter:2, type:"single",
    q:"SD card data folders are automatically created every ____.",
    opts:["1 hour", "4 hours", "8 hours", "24 hours"],
    ans:"C",
    exp:"A new folder is created every 8 hours; the timestamp = recording start time." },
  { id:"Q67", chapter:2, type:"single",
    q:"The data parsing chain on the upper-PC is ____.",
    opts:["bin file → upper-PC software → CSC / summary", "CSC → bin → SD card", "summary → bin → upper-PC", "SD card → CSC → bin"],
    ans:"A",
    exp:"SD card bin file → parsed by the upper-PC software → CSC data / summary file." },
  { id:"Q68", chapter:2, type:"single",
    q:"The cumulative charge / discharge energy is found in the ____.",
    opts:["bin file", "BAU summary file", "SD card label", "CSC raw file only"],
    ans:"B",
    exp:"The BAU summary file holds the two cumulative energy columns." },
  { id:"Q69", chapter:2, type:"single",
    q:"To find the exact point where charge/discharge truly starts, you should read the ____ column.",
    opts:["SOC", "current", "temperature", "voltage only"],
    ans:"B",
    exp:"Look at the current column — current jumping up from 0 marks the real start." },
  { id:"Q70", chapter:2, type:"single",
    q:"In the Australia case, actual discharge was 3166 vs the 3363 standard, yet RTE was 96.38% and passed. Why?",
    opts:["RTE depends on the charge/discharge ratio, not the absolute capacity", "The measurement was wrong", "The capacity was actually fine", "RTE was faked"],
    ans:"A",
    exp:"RTE depends on the charge/discharge ratio, not the single-cycle capacity — so capacity must be checked separately." },
  { id:"Q71", chapter:2, type:"single",
    q:"The root cause in the Australia case was ____.",
    opts:["cell voltage difference (consistency)", "PCS failure", "high temperature", "wrong current setting"],
    ans:"A",
    exp:"Root cause was a large cell voltage difference (poor consistency), confirmed via the SOC-OCV table." },
  { id:"Q72", chapter:2, type:"single",
    q:"In the Australia case, about how much energy was stuck in the weakest cells and could not be released?",
    opts:["~5%", "~15%", "~30%", "~50%"],
    ans:"B",
    exp:"About 15% of energy was stuck (≈ 555 kWh out of ~3700 kWh)." },
  { id:"Q73", chapter:2, type:"single",
    q:"The Maintenance (one-click maintenance) function ensures that ____.",
    opts:["every RACK can charge to cell 3.62V", "every PCS keeps working", "temperature stays low", "discharge becomes faster"],
    ans:"A",
    exp:"Maintenance ensures every RACK reaches a full charge (cell 3.62V)." },
  { id:"Q74", chapter:2, type:"single",
    q:"How often should the Maintenance function be enabled?",
    opts:["Every cycle", "Once at the first full charge; later RTE cycles do not need it", "Never", "Every 8 hours"],
    ans:"B",
    exp:"Enable once at the first full charge; subsequent RTE tests do not need it." },
  { id:"Q75", chapter:2, type:"single",
    q:"In the RPC re-analysis of the Australia case, the late-stage current reduction ____.",
    opts:["reduced the total released energy", "increased the total released energy (3166 → 3500+)", "had no effect", "caused a fault"],
    ans:"B",
    exp:"Lower current releases more energy, so capacity was corrected up to 3500+ kWh." },
  { id:"Q76", chapter:2, type:"truefalse",
    q:"RTE can be measured by charging to 100% and discharging to only 50%.",
    ans:false,
    exp:"False. RTE requires a full charge and full discharge cycle." },
  { id:"Q77", chapter:2, type:"truefalse",
    q:"RTE = discharge energy ÷ charge energy.",
    ans:true,
    exp:"True." },
  { id:"Q78", chapter:2, type:"truefalse",
    q:"During full charge, at cell 3.6V the current is reduced (down to 0.1P).",
    ans:true,
    exp:"True." },
  { id:"Q79", chapter:2, type:"truefalse",
    q:"The full-discharge cutoff voltage is 2.8V per cell.",
    ans:true,
    exp:"True." },
  { id:"Q80", chapter:2, type:"truefalse",
    q:"Looking up the OCV-SOC table requires the cell to rest for at least 2 hours.",
    ans:true,
    exp:"True." },
  { id:"Q81", chapter:2, type:"truefalse",
    q:"A higher discharge current releases more energy.",
    ans:false,
    exp:"False. Higher current releases less energy; lower current releases more." },
  { id:"Q82", chapter:2, type:"truefalse",
    q:"The standard testing temperature for RTE is 25℃.",
    ans:true,
    exp:"True." },
  { id:"Q83", chapter:2, type:"truefalse",
    q:"A cell voltage difference greater than 100 mV is normal and needs no action.",
    ans:false,
    exp:"False. >100 mV is abnormal and requires balancing." },
  { id:"Q84", chapter:2, type:"truefalse",
    q:"SD card data folders are generated every 8 hours.",
    ans:true,
    exp:"True." },
  { id:"Q85", chapter:2, type:"truefalse",
    q:"The cumulative charge/discharge energy is stored in the BAU summary file.",
    ans:true,
    exp:"True." },
  { id:"Q86", chapter:2, type:"truefalse",
    q:"A battery system can pass RTE but still fail the capacity requirement.",
    ans:true,
    exp:"True — RTE and capacity are independent and must be checked separately." },
  { id:"Q87", chapter:2, type:"truefalse",
    q:"To find when charging truly begins, you should look at the current column.",
    ans:true,
    exp:"True." },
  { id:"Q88", chapter:2, type:"truefalse",
    q:"The Maintenance function should be enabled on every single RTE cycle.",
    ans:false,
    exp:"False. It is enabled once at the first full charge; later cycles do not need it." },
  { id:"Q89", chapter:2, type:"truefalse",
    q:"Nominal total energy = cell V × cell Ah × cells/PACK × PACKs/RACK × RACKs.",
    ans:true,
    exp:"True." },
  { id:"Q90", chapter:2, type:"truefalse",
    q:"The system overall efficiency is the product of DC-side efficiency, PCS efficiency and transformer efficiency.",
    ans:true,
    exp:"True." },
  { id:"Q91", chapter:2, type:"multi",
    q:"Which of the following are the four factors affecting RTE?",
    opts:["Cell consistency (voltage difference)", "Charge/discharge rate (current)", "Temperature", "Time (rest duration)"],
    ans:["A", "B", "C", "D"],
    exp:"The four factors: consistency, rate, temperature, time." },
  { id:"Q92", chapter:2, type:"multi",
    q:"The full charge–full discharge site procedure includes which steps (in order)?",
    opts:["Discharge to SOC = 0", "Charge to SOC = 100%", "Rest ≥ 2 hours", "Discharge to SOC = 0 again"],
    ans:["A", "B", "C", "D"],
    exp:"Full sequence: empty → full charge → rest → full discharge → rest." },
  { id:"Q93", chapter:2, type:"multi",
    q:"Which steps are part of the full-charge strategy?",
    opts:["Constant-power charge first", "At cell 3.6V reduce current to 0.1P", "Charge to 3.62V", "Calibrate SOC to 100%"],
    ans:["A", "B", "C", "D"],
    exp:"All are correct steps of the full-charge strategy." },
  { id:"Q94", chapter:2, type:"multi",
    q:"Which are valid SOC calibration methods?",
    opts:["Rest + OCV-SOC table lookup (static)", "Full-charge / full-discharge anchoring (dynamic)", "Random guess", "Only at factory"],
    ans:["A", "B"],
    exp:"Two methods: static (OCV table) and dynamic (anchor at 0% / 100%)." },
  { id:"Q95", chapter:2, type:"multi",
    q:"Which files / steps are involved in the data parsing chain?",
    opts:["SD card bin file", "Upper-PC parsing software", "CSC data", "BAU summary file"],
    ans:["A", "B", "C", "D"],
    exp:"bin → upper-PC → CSC / BAU summary." },
  { id:"Q96", chapter:2, type:"multi",
    q:"Which statements about SD card data folders are correct?",
    opts:["A new folder is created every 8 hours", "The folder timestamp equals the recording start time", "A folder appears only after 8 hours of recording", "Folders are created every 1 hour"],
    ans:["A", "B", "C"],
    exp:"Every 8h, timestamp = start; if recording < 8h no folder appears yet." },
  { id:"Q97", chapter:2, type:"multi",
    q:"In the Australia anomaly case, which observations were made?",
    opts:["Actual discharge 3166 < required 3363", "RTE 96.38% passed", "Cell voltage difference > 100 mV", "About 15% of energy stuck in the weakest cells"],
    ans:["A", "B", "C", "D"],
    exp:"All are observations from the Australia case." },
  { id:"Q98", chapter:2, type:"multi",
    q:"Which statements about charge/discharge energy calculation are correct?",
    opts:["Charge energy = end-of-charge cumulative − SOC=0 cumulative", "Discharge energy = end-of-discharge cumulative − start-of-discharge cumulative", "Cumulative energy keeps accumulating across cycles", "Charge energy should be read directly from the SOC column"],
    ans:["A", "B", "C"],
    exp:"Use the cumulative energy columns and take differences; do not read energy from the SOC column." },
  { id:"Q99", chapter:2, type:"multi",
    q:"Which of the following determine which OCV-SOC lookup table is used?",
    opts:["Cell model (e.g. 280Ah, 315Ah)", "Temperature (e.g. 10/25/35/45℃)", "Rest duration", "Current rate at that instant"],
    ans:["A", "B"],
    exp:"Different cell models and temperatures use different tables; rest ≥ 2h is a precondition (not a table axis)." },
  { id:"Q100", chapter:2, type:"multi",
    q:"Which statements about RTE and capacity are correct?",
    opts:["RTE depends on the charge/discharge ratio, not the absolute capacity", "A system can pass RTE but still fail capacity", "Capacity must be checked separately", "Passing RTE automatically means the capacity is fine"],
    ans:["A", "B", "C"],
    exp:"RTE and capacity are independent; both must be verified." }

];
