/* ============================================================
   ENERGY STORAGE SYSTEM TESTING — QUESTION BANK (English)
   ============================================================
   HOW TO UPDATE THE BANK:
   - Edit THIS file (quiz-en.js), save, then reopen exam-en.html.
   - You do NOT need to touch exam-en.html.
   -
   - Each question is an object. Three types are supported:
   -
   -   single:    { id, chapter, type:'single', q, opts:[...], ans:'B', exp }
   -   truefalse: { id, chapter, type:'truefalse', q, ans:true, exp }
   -   multi:     { id, chapter, type:'multi', q, opts:[...], ans:['A','C'], exp }
   -
   - - ans letters map to opts order: A = 1st option, B = 2nd, ...
   - - truefalse has NO opts (True/False shown automatically); ans is true or false.
   - - chapter must match one of the CHAPTERS ids below.
   ============================================================ */

const CHAPTERS = [
  { id: 1, title: "Energy Storage System Testing" },
  { id: 2, title: "RTE Data Analysis" },
  { id: 3, title: "F-STOP Function" }
];

const QUESTIONS = [
  { id:"Q01", chapter:1, type:"single",
    q:"According to DL/T 1194-2012, a BESS consists of a storage battery and a _____.",
    opts:["supercapacitor","shunt voltage-type converter","flywheel","uninterruptible power supply (UPS)"],
    ans:"B",
    exp:"A BESS is an energy storage system consisting of a battery and a shunt (parallel) voltage-type converter (DL/T 1194-2012, 6.22)." },

  { id:"Q02", chapter:1, type:"single",
    q:"The first-level pipeline of the liquid-cooling system adopts which scheme?",
    opts:["top-in bottom-out","bottom-in bottom-out","top-in top-out","side-in side-out"],
    ans:"B",
    exp:"The first-level pipeline uses a 'bottom-in bottom-out' scheme to ensure uniform PACK flow; pipes are wrapped with insulation foam to prevent condensation." },

  { id:"Q03", chapter:1, type:"single",
    q:"The fire suppression system of an electrochemical storage cabin consists of how many main parts?",
    opts:["two","three","four","five"],
    ans:"C",
    exp:"Four parts: fire main engine; cabin-level combustible detector / smoke / temperature sensors; sound-light alarm + intake/exhaust system; water spray system." },

  { id:"Q04", chapter:1, type:"single",
    q:"What is the main function of the Local Controller (LC)?",
    opts:["AC/DC power conversion","monitor local device status and execute strategy-based actions, plus record data","accept external grid dispatch","acquire cell temperature only"],
    ans:"B",
    exp:"The LC monitors local device status, performs actions according to strategy, and records data." },

  { id:"Q05", chapter:1, type:"truefalse",
    q:"A DC cabin integrates the PCS inside the cabin.",
    ans:false,
    exp:"False. A DC cabin has the PCS external; an AC cabin integrates the PCS (and an optional transformer) inside." },

  { id:"Q06", chapter:1, type:"truefalse",
    q:"An AC cabin can independently realize energy storage, conversion and release.",
    ans:true,
    exp:"True. An AC cabin integrates the battery array, BMS, auxiliary systems, PCS and an optional transformer, so it can independently store/convert/release energy." },

  { id:"Q07", chapter:1, type:"truefalse",
    q:"The EMS is responsible for charge/discharge control and accepts external dispatch.",
    ans:true,
    exp:"True. The EMS handles system charge/discharge control, accepts external scheduling, and interacts with local controllers." },

  { id:"Q08", chapter:1, type:"multi",
    q:"Which of the following are typical components of a battery cabin?",
    opts:["Cells / modules / racks","BMS and high-voltage box (BDU)","Distribution cabinet and bus cabinet","Liquid cooling / air conditioner and fire protection system"],
    ans:["A","B","C","D"],
    exp:"A battery cabin contains modules, AC, battery racks/wiring, fire protection, BDU, racks, cells, BMS, cooling machine, and distribution/bus cabinets." },
  { id:"Q09", chapter:1, type:"single",
    q:"In the BMS three-level architecture, which level acquires Pack cell voltage/current/temperature and performs thermal management and passive balancing?",
    opts:["BAU","BCU","BMU","PCS"],
    ans:"C",
    exp:"BMU acquires Pack cell data and provides thermal management and passive balancing." },

  { id:"Q10", chapter:1, type:"single",
    q:"What is the BCU voltage acquisition range?",
    opts:["0–50V","9–32V","50V–1500V","0–1500V"],
    ans:"C",
    exp:"BCU voltage acquisition is 50V–1500V (±0.5%); 9–32V is its working voltage — do not confuse them." },

  { id:"Q11", chapter:1, type:"single",
    q:"When severe over-voltage, under-voltage, over-current (short circuit) or leakage (insulation) occurs, which level controls the cluster breaking?",
    opts:["BMU","BCU","BAU","EMS"],
    ans:"B",
    exp:"The BCU controls the breaking of the battery cluster under such abnormal faults." },

  { id:"Q12", chapter:1, type:"single",
    q:"Which level performs numerical calculation, performance analysis and alarm processing on data uploaded by BMU and BCU?",
    opts:["BMU","BCU","BAU","PCS"],
    ans:"C",
    exp:"The BAU performs calculation / analysis / alarm / record storage and linkage control with PCS and EMS." },

  { id:"Q13", chapter:1, type:"single",
    q:"What is the BMU balancing current?",
    opts:["10mA","50mA","100mA","500mA"],
    ans:"C",
    exp:"The BMU uses passive balancing with a current of 100mA." },

  { id:"Q14", chapter:1, type:"single",
    q:"How many cells does a BMU manage?",
    opts:["24","36","52","100"],
    ans:"C",
    exp:"A BMU manages 52 cells (voltage balancing range 0–5V, passive balancing current 100mA)." },

  { id:"Q15", chapter:1, type:"truefalse",
    q:"The BMU uses active balancing.",
    ans:false,
    exp:"False. The BMU uses passive balancing (100mA)." },

  { id:"Q16", chapter:1, type:"truefalse",
    q:"The BCU controls cluster breaking when serious over-voltage, under-voltage, over-current or leakage occurs.",
    ans:true,
    exp:"True." },

  { id:"Q17", chapter:1, type:"truefalse",
    q:"The BAU performs linkage control with PCS and EMS.",
    ans:true,
    exp:"True. The BAU links with PCS, EMS, etc." },
  { id:"Q18", chapter:1, type:"single",
    q:"What is the core power device inside the PCS for AC/DC conversion?",
    opts:["IGBT","relay","fuse","contactor"],
    ans:"A",
    exp:"The IGBT is the core power switching device implementing AC/DC conversion inside the PCS." },

  { id:"Q19", chapter:1, type:"single",
    q:"A liquid-cooled cabin has a rated energy of 3354 kWh. At the 0.5P rate, what is the maximum operating power?",
    opts:["838.5 kW","1677 kW","3354 kW","6717 kW"],
    ans:"B",
    exp:"0.5P = 3354 × 0.5 = 1677 kW." },

  { id:"Q20", chapter:1, type:"single",
    q:"A 1P rate means the system can fully discharge the rated energy in _____.",
    opts:["0.5 hour","1 hour","2 hours","4 hours"],
    ans:"B",
    exp:"1P means fully discharging the rated energy in 1 hour; 0.5P takes 2 hours." },

  { id:"Q21", chapter:1, type:"single",
    q:"What is the purpose of anti-islanding protection?",
    opts:["improve efficiency","stop feeding power to the grid when the grid is down","balance cells","limit charge current"],
    ans:"B",
    exp:"Anti-islanding protection makes the PCS stop feeding the grid when it is de-energized, protecting maintenance personnel." },

  { id:"Q22", chapter:1, type:"truefalse",
    q:"The PCS can regulate both active and reactive power.",
    ans:true,
    exp:"True. The PCS can rapidly regulate active and reactive power exchange with the AC system." },

  { id:"Q23", chapter:1, type:"truefalse",
    q:"In off-grid mode, the PCS uses V/f control to maintain voltage amplitude and frequency.",
    ans:true,
    exp:"True. Off-grid V/f control keeps voltage amplitude (V) and frequency (F) constant." },

  { id:"Q24", chapter:1, type:"multi",
    q:"Which of the following are PCS control functions?",
    opts:["Grid-connected constant-power charge/discharge","Grid-connected constant voltage","Current-limiting charge","Off-grid V/f control","Reactive power regulation"],
    ans:["A","B","C","D","E"],
    exp:"All are PCS control functions (anti-islanding protection is also listed under control in the course)." },

  { id:"Q25", chapter:1, type:"multi",
    q:"Which of the following are PCS protection functions?",
    opts:["Battery polarity reverse protection","DC over-voltage/over-current protection","Grid over/under-voltage protection","Grid over/under-frequency protection","IGBT module over-current/over-temperature protection"],
    ans:["A","B","C","D","E"],
    exp:"All are PCS protection functions (plus grid over-current protection)." },
  { id:"Q26", chapter:1, type:"single",
    q:"The insulation resistance test is based on which law?",
    opts:["Kirchhoff's law","Ohm's law","Joule's law","Lenz's law"],
    ans:"B",
    exp:"Apply a voltage → measure current → calculate R = U/I using Ohm's law." },

  { id:"Q27", chapter:1, type:"single",
    q:"In a withstand voltage test, pass/fail is judged by _____.",
    opts:["the insulation resistance value","comparing leakage current with a judgment current","the ground resistance","the temperature rise"],
    ans:"B",
    exp:"If leakage current < judgment value → pass; if greater → cut off the voltage and alarm (breakdown)." },

  { id:"Q28", chapter:1, type:"single",
    q:"What does the ground continuity test mainly measure?",
    opts:["insulation resistance","leakage current","ground resistance","contact voltage"],
    ans:"C",
    exp:"Inject a current, measure voltage/current, and calculate the ground resistance; criterion is an upper limit." },

  { id:"Q29", chapter:1, type:"single",
    q:"What is the maximum current of the short-circuit test machine?",
    opts:["1200 A","6000 A","12000 A","200 kN"],
    ans:"C",
    exp:"Short-circuit tester: 0–100 mΩ, 0–12000 A. 200 kN is the pressure of the needling/extrusion tester." },

  { id:"Q30", chapter:1, type:"single",
    q:"What is the pressure range of the needling/extrusion test machine?",
    opts:["0–100 kN","0–200 kN","0–1000 kN","0–12000 A"],
    ans:"B",
    exp:"Needling/extrusion tester: speed 0.05–100 mm/s, pressure 0–200 kN." },

  { id:"Q31", chapter:1, type:"truefalse",
    q:"In a withstand voltage test, if the leakage current is greater than the judgment current, the device passes.",
    ans:false,
    exp:"False. It fails — the test voltage is cut off and a sound-light alarm is issued." },

  { id:"Q32", chapter:1, type:"truefalse",
    q:"Insulation resistance is calculated by applying a voltage, measuring the resulting current, and using Ohm's law.",
    ans:true,
    exp:"True." },

  { id:"Q33", chapter:1, type:"truefalse",
    q:"The pass criterion of the ground continuity test is a resistance upper limit (the lower the ground resistance, the better).",
    ans:true,
    exp:"True. A lower ground resistance means fault current can be safely discharged." },

  { id:"Q34", chapter:1, type:"multi",
    q:"Which of the following are the three electrical safety (dielectric) tests?",
    opts:["Insulation resistance test","Withstand voltage test","Ground continuity test","Vibration test","Drop test"],
    ans:["A","B","C"],
    exp:"The three safety tests are insulation resistance, withstand voltage and ground continuity; vibration/drop are mechanical safety tests." },
  { id:"Q35", chapter:1, type:"single",
    q:"The V-model evolved from which development model?",
    opts:["Waterfall model","Rapid Application Development (RAD) model","Spiral model","Agile model"],
    ans:"B",
    exp:"The V-model evolved from the RAD (Rapid Application Development) model." },

  { id:"Q36", chapter:1, type:"single",
    q:"In performance testing, at least how many full charge/discharge cycles must be performed using the PCS?",
    opts:["1","2","3","5"],
    ans:"C",
    exp:"At least 3 complete charge/discharge cycles are required." },

  { id:"Q37", chapter:1, type:"single",
    q:"The Japanese 'Fire Service Hazard 303' standard corresponds to which test?",
    opts:["vibration test","3-meter drop test","needling test","fire test"],
    ans:"B",
    exp:"Japanese 'Fire Service Hazard 303' corresponds to a 3-meter drop test." },

  { id:"Q38", chapter:1, type:"truefalse",
    q:"Energy storage system tests can be classified by test object, test type and test stage.",
    ans:true,
    exp:"True — three classification dimensions." },

  { id:"Q39", chapter:1, type:"truefalse",
    q:"The right side of the V-model includes unit, integration, system and acceptance testing.",
    ans:true,
    exp:"True." },

  { id:"Q40", chapter:1, type:"multi",
    q:"Which of the following are cell-level electrical safety tests?",
    opts:["Overcharge","Overdischarge","Short circuit","Thermal runaway","Heating"],
    ans:["A","B","C","D"],
    exp:"Cell electrical safety: overcharge, overdischarge, short circuit, thermal runaway. Heating is an environmental safety test." },

  { id:"Q41", chapter:1, type:"multi",
    q:"Which of the following are cell-level mechanical safety tests?",
    opts:["Vibration","Drop","Extrusion","Needling","Heating"],
    ans:["A","B","C","D"],
    exp:"Cell mechanical safety: vibration, drop, extrusion, needling. Heating is environmental." },

  { id:"Q42", chapter:1, type:"multi",
    q:"Which of the following are typical DI (digital input) signals?",
    opts:["AC power-on","Mains switch closed","Door access","Emergency stop","Fire alarm"],
    ans:["A","B","C","D","E"],
    exp:"DI includes AC power-on, mains switch, door access, ATS signal, isolation switch, fuse, SPD, water immersion, emergency stop, fire, etc." },

  { id:"Q43", chapter:1, type:"multi",
    q:"Which of the following are typical DO (digital output) signals?",
    opts:["DC power-on","DC fault","Total power cut-off","Stop BMS","Stop PCS"],
    ans:["A","B","C","D","E"],
    exp:"DO includes DC power-on, DC fault, total power cut-off, UPS cut-off, stop BMS, stop PCS, etc." },
  { id:"Q44", chapter:1, type:"single",
    q:"Which standard is the evaluation method for thermal runaway fire spread in battery energy storage systems?",
    opts:["UL 1973","UL 9540","UL 9540A","UL 1642"],
    ans:"C",
    exp:"UL 9540A evaluates thermal runaway fire spread (UL 9540 is the system safety standard)." },

  { id:"Q45", chapter:1, type:"single",
    q:"What is the maximum DC voltage covered by IEC 63056?",
    opts:["1000 V","1200 V","1500 V","3000 V"],
    ans:"C",
    exp:"IEC 63056 applies to secondary lithium batteries for power storage with a maximum DC voltage of 1500 V." },

  { id:"Q46", chapter:1, type:"single",
    q:"GB/T 36276 is a national standard for which market?",
    opts:["EU","Japan","North America","China"],
    ans:"D",
    exp:"GB/T 36276 is the Chinese national standard test for energy storage batteries." },

  { id:"Q47", chapter:1, type:"truefalse",
    q:"UL 9540 is the world's first safety standard for energy storage systems.",
    ans:true,
    exp:"True." },

  { id:"Q48", chapter:1, type:"truefalse",
    q:"UN38.3 is the international transport safety test standard for secondary lithium batteries.",
    ans:true,
    exp:"True." },

  { id:"Q49", chapter:1, type:"multi",
    q:"Energy storage certification is mainly divided into which markets?",
    opts:["CN (China)","JP (Japan)","NA (North America)","EU (Europe)"],
    ans:["A","B","C","D"],
    exp:"Four markets: CN, JP, NA, EU." },

  { id:"Q50", chapter:1, type:"multi",
    q:"Which of the following are common North American (NA) energy storage certification standards?",
    opts:["UL 1973","UL 9540","UL 9540A","UL 1642","IEC 62619"],
    ans:["A","B","C","D"],
    exp:"NA uses UL 1973 / 9540 / 9540A / 1642; IEC 62619 belongs to EU." }
,

  /* ---------- Chapter 2: RTE Data Analysis ---------- */
  { id:"Q51", chapter:2, type:"single",
    q:"RTE (Round Trip Efficiency) is defined as ____.",
    opts:["discharge energy ÷ charge energy", "charge energy ÷ discharge energy", "discharge power ÷ charge power", "charge energy × discharge energy"],
    ans:"A",
    exp:"RTE = discharge energy ÷ charge energy, measured over a full charge–full discharge cycle." },
  { id:"Q52", chapter:2, type:"single",
    q:"RTE must be measured under a _____ condition.",
    opts:["full charge and full discharge cycle", "charge to 100% and discharge to 50%", "partial charge only", "constant-voltage only"],
    ans:"A",
    exp:"RTE requires a full 0%↔100% charge–discharge cycle." },
  { id:"Q53", chapter:2, type:"single",
    q:"On site, the battery typically starts at about what SOC before the RTE test?",
    opts:["10%", "30%", "50%", "80%"],
    ans:"B",
    exp:"Site batteries usually start around SOC 30%." },
  { id:"Q54", chapter:2, type:"single",
    q:"During full charge at constant power, the current is reduced to 0.1P at cell voltage ____.",
    opts:["3.0V", "3.2V", "3.6V", "3.62V"],
    ans:"C",
    exp:"At cell 3.6V the current is stepped down to 0.1P; charging then continues to 3.62V." },
  { id:"Q55", chapter:2, type:"single",
    q:"Full charge calibrates SOC to 100% at cell voltage ____.",
    opts:["3.6V", "3.62V", "2.8V", "2.9V"],
    ans:"B",
    exp:"At cell 3.62V, SOC is calibrated to 100%." },
  { id:"Q56", chapter:2, type:"single",
    q:"During full discharge, the cutoff cell voltage (SOC = 0) is ____.",
    opts:["2.8V", "2.9V", "3.0V", "3.6V"],
    ans:"A",
    exp:"Full discharge ends at cell 2.8V, calibrated to SOC = 0%." },
  { id:"Q57", chapter:2, type:"single",
    q:"Before looking up the OCV-SOC table, the cell must rest for at least ____.",
    opts:["10 minutes", "30 minutes", "1 hour", "2 hours"],
    ans:"D",
    exp:"OCV lookup requires a rest of at least 2 hours for the voltage to stabilize." },
  { id:"Q58", chapter:2, type:"single",
    q:"What is the standard testing temperature for RTE?",
    opts:["20℃", "25℃", "30℃", "22℃"],
    ans:"B",
    exp:"The standard test temperature is 25℃." },
  { id:"Q59", chapter:2, type:"single",
    q:"Which range is the suitable temperature window for RTE testing?",
    opts:["0–10℃", "15–35℃", "40–60℃", "-10–0℃"],
    ans:"B",
    exp:"The suitable range is 15–35℃ (customers often specify 22–28℃)." },
  { id:"Q60", chapter:2, type:"single",
    q:"A cell-to-cell voltage difference greater than ____ is considered abnormal and requires balancing.",
    opts:["10 mV", "50 mV", "100 mV", "500 mV"],
    ans:"C",
    exp:"A voltage difference > 100 mV is abnormal; balancing is required." },
  { id:"Q61", chapter:2, type:"single",
    q:"How does the charge/discharge rate affect the released energy?",
    opts:["Higher current releases more energy", "Higher current releases less energy", "Current has no effect", "Lower current releases less energy"],
    ans:"B",
    exp:"Higher current (e.g. 1P) releases less energy; lower current releases more." },
  { id:"Q62", chapter:2, type:"single",
    q:"In this course the cell is LFP with nominal voltage / capacity ____.",
    opts:["3.0V / 200Ah", "3.2V / 280Ah", "3.7V / 280Ah", "3.2V / 100Ah"],
    ans:"B",
    exp:"LFP cell, nominal 3.2V / 280Ah." },
  { id:"Q63", chapter:2, type:"single",
    q:"One PACK consists of how many cells in series?",
    opts:["12", "24", "48", "52"],
    ans:"D",
    exp:"A PACK = 52 cells in series." },
  { id:"Q64", chapter:2, type:"single",
    q:"Which formula gives the nominal total energy?",
    opts:["cell V × cell Ah × cells/PACK × PACKs/RACK × RACKs", "cell V × cell Ah only", "cell Ah × RACKs", "cell V × PACKs"],
    ans:"A",
    exp:"Nominal total energy = cell V × cell Ah × cells/PACK × PACKs/RACK × RACKs." },
  { id:"Q65", chapter:2, type:"single",
    q:"Using 3.2V × 280Ah × 52 × 8 × 10, the nominal total energy is about ____.",
    opts:["~2000 kWh", "~3700 kWh", "~5000 kWh", "~1000 kWh"],
    ans:"B",
    exp:"≈ 3727 kWh (about 3700 kWh)." },
  { id:"Q66", chapter:2, type:"single",
    q:"SD card data folders are automatically created every ____.",
    opts:["1 hour", "4 hours", "8 hours", "24 hours"],
    ans:"C",
    exp:"A new folder is created every 8 hours; the timestamp = recording start time." },
  { id:"Q67", chapter:2, type:"single",
    q:"The data parsing chain on the upper-PC is ____.",
    opts:["bin file → upper-PC software → CSC / summary", "CSC → bin → SD card", "summary → bin → upper-PC", "SD card → CSC → bin"],
    ans:"A",
    exp:"SD card bin file → parsed by the upper-PC software → CSC data / summary file." },
  { id:"Q68", chapter:2, type:"single",
    q:"The cumulative charge / discharge energy is found in the ____.",
    opts:["bin file", "BAU summary file", "SD card label", "CSC raw file only"],
    ans:"B",
    exp:"The BAU summary file holds the two cumulative energy columns." },
  { id:"Q69", chapter:2, type:"single",
    q:"To find the exact point where charge/discharge truly starts, you should read the ____ column.",
    opts:["SOC", "current", "temperature", "voltage only"],
    ans:"B",
    exp:"Look at the current column — current jumping up from 0 marks the real start." },
  { id:"Q70", chapter:2, type:"single",
    q:"In the Australia case, actual discharge was 3166 vs the 3363 standard, yet RTE was 96.38% and passed. Why?",
    opts:["RTE depends on the charge/discharge ratio, not the absolute capacity", "The measurement was wrong", "The capacity was actually fine", "RTE was faked"],
    ans:"A",
    exp:"RTE depends on the charge/discharge ratio, not the single-cycle capacity — so capacity must be checked separately." },
  { id:"Q71", chapter:2, type:"single",
    q:"The root cause in the Australia case was ____.",
    opts:["cell voltage difference (consistency)", "PCS failure", "high temperature", "wrong current setting"],
    ans:"A",
    exp:"Root cause was a large cell voltage difference (poor consistency), confirmed via the SOC-OCV table." },
  { id:"Q72", chapter:2, type:"single",
    q:"In the Australia case, about how much energy was stuck in the weakest cells and could not be released?",
    opts:["~5%", "~15%", "~30%", "~50%"],
    ans:"B",
    exp:"About 15% of energy was stuck (≈ 555 kWh out of ~3700 kWh)." },
  { id:"Q73", chapter:2, type:"single",
    q:"The Maintenance (one-click maintenance) function ensures that ____.",
    opts:["every RACK can charge to cell 3.62V", "every PCS keeps working", "temperature stays low", "discharge becomes faster"],
    ans:"A",
    exp:"Maintenance ensures every RACK reaches a full charge (cell 3.62V)." },
  { id:"Q74", chapter:2, type:"single",
    q:"How often should the Maintenance function be enabled?",
    opts:["Every cycle", "Once at the first full charge; later RTE cycles do not need it", "Never", "Every 8 hours"],
    ans:"B",
    exp:"Enable once at the first full charge; subsequent RTE tests do not need it." },
  { id:"Q75", chapter:2, type:"single",
    q:"In the RPC re-analysis of the Australia case, the late-stage current reduction ____.",
    opts:["reduced the total released energy", "increased the total released energy (3166 → 3500+)", "had no effect", "caused a fault"],
    ans:"B",
    exp:"Lower current releases more energy, so capacity was corrected up to 3500+ kWh." },
  { id:"Q76", chapter:2, type:"truefalse",
    q:"RTE can be measured by charging to 100% and discharging to only 50%.",
    ans:false,
    exp:"False. RTE requires a full charge and full discharge cycle." },
  { id:"Q77", chapter:2, type:"truefalse",
    q:"RTE = discharge energy ÷ charge energy.",
    ans:true,
    exp:"True." },
  { id:"Q78", chapter:2, type:"truefalse",
    q:"During full charge, at cell 3.6V the current is reduced (down to 0.1P).",
    ans:true,
    exp:"True." },
  { id:"Q79", chapter:2, type:"truefalse",
    q:"The full-discharge cutoff voltage is 2.8V per cell.",
    ans:true,
    exp:"True." },
  { id:"Q80", chapter:2, type:"truefalse",
    q:"Looking up the OCV-SOC table requires the cell to rest for at least 2 hours.",
    ans:true,
    exp:"True." },
  { id:"Q81", chapter:2, type:"truefalse",
    q:"A higher discharge current releases more energy.",
    ans:false,
    exp:"False. Higher current releases less energy; lower current releases more." },
  { id:"Q82", chapter:2, type:"truefalse",
    q:"The standard testing temperature for RTE is 25℃.",
    ans:true,
    exp:"True." },
  { id:"Q83", chapter:2, type:"truefalse",
    q:"A cell voltage difference greater than 100 mV is normal and needs no action.",
    ans:false,
    exp:"False. >100 mV is abnormal and requires balancing." },
  { id:"Q84", chapter:2, type:"truefalse",
    q:"SD card data folders are generated every 8 hours.",
    ans:true,
    exp:"True." },
  { id:"Q85", chapter:2, type:"truefalse",
    q:"The cumulative charge/discharge energy is stored in the BAU summary file.",
    ans:true,
    exp:"True." },
  { id:"Q86", chapter:2, type:"truefalse",
    q:"A battery system can pass RTE but still fail the capacity requirement.",
    ans:true,
    exp:"True — RTE and capacity are independent and must be checked separately." },
  { id:"Q87", chapter:2, type:"truefalse",
    q:"To find when charging truly begins, you should look at the current column.",
    ans:true,
    exp:"True." },
  { id:"Q88", chapter:2, type:"truefalse",
    q:"The Maintenance function should be enabled on every single RTE cycle.",
    ans:false,
    exp:"False. It is enabled once at the first full charge; later cycles do not need it." },
  { id:"Q89", chapter:2, type:"truefalse",
    q:"Nominal total energy = cell V × cell Ah × cells/PACK × PACKs/RACK × RACKs.",
    ans:true,
    exp:"True." },
  { id:"Q90", chapter:2, type:"truefalse",
    q:"The system overall efficiency is the product of DC-side efficiency, PCS efficiency and transformer efficiency.",
    ans:true,
    exp:"True." },
  { id:"Q91", chapter:2, type:"multi",
    q:"Which of the following are the four factors affecting RTE?",
    opts:["Cell consistency (voltage difference)", "Charge/discharge rate (current)", "Temperature", "Time (rest duration)"],
    ans:["A", "B", "C", "D"],
    exp:"The four factors: consistency, rate, temperature, time." },
  { id:"Q92", chapter:2, type:"multi",
    q:"The full charge–full discharge site procedure includes which steps (in order)?",
    opts:["Discharge to SOC = 0", "Charge to SOC = 100%", "Rest ≥ 2 hours", "Discharge to SOC = 0 again"],
    ans:["A", "B", "C", "D"],
    exp:"Full sequence: empty → full charge → rest → full discharge → rest." },
  { id:"Q93", chapter:2, type:"multi",
    q:"Which steps are part of the full-charge strategy?",
    opts:["Constant-power charge first", "At cell 3.6V reduce current to 0.1P", "Charge to 3.62V", "Calibrate SOC to 100%"],
    ans:["A", "B", "C", "D"],
    exp:"All are correct steps of the full-charge strategy." },
  { id:"Q94", chapter:2, type:"multi",
    q:"Which are valid SOC calibration methods?",
    opts:["Rest + OCV-SOC table lookup (static)", "Full-charge / full-discharge anchoring (dynamic)", "Random guess", "Only at factory"],
    ans:["A", "B"],
    exp:"Two methods: static (OCV table) and dynamic (anchor at 0% / 100%)." },
  { id:"Q95", chapter:2, type:"multi",
    q:"Which files / steps are involved in the data parsing chain?",
    opts:["SD card bin file", "Upper-PC parsing software", "CSC data", "BAU summary file"],
    ans:["A", "B", "C", "D"],
    exp:"bin → upper-PC → CSC / BAU summary." },
  { id:"Q96", chapter:2, type:"multi",
    q:"Which statements about SD card data folders are correct?",
    opts:["A new folder is created every 8 hours", "The folder timestamp equals the recording start time", "A folder appears only after 8 hours of recording", "Folders are created every 1 hour"],
    ans:["A", "B", "C"],
    exp:"Every 8h, timestamp = start; if recording < 8h no folder appears yet." },
  { id:"Q97", chapter:2, type:"multi",
    q:"In the Australia anomaly case, which observations were made?",
    opts:["Actual discharge 3166 < required 3363", "RTE 96.38% passed", "Cell voltage difference > 100 mV", "About 15% of energy stuck in the weakest cells"],
    ans:["A", "B", "C", "D"],
    exp:"All are observations from the Australia case." },
  { id:"Q98", chapter:2, type:"multi",
    q:"Which statements about charge/discharge energy calculation are correct?",
    opts:["Charge energy = end-of-charge cumulative − SOC=0 cumulative", "Discharge energy = end-of-discharge cumulative − start-of-discharge cumulative", "Cumulative energy keeps accumulating across cycles", "Charge energy should be read directly from the SOC column"],
    ans:["A", "B", "C"],
    exp:"Use the cumulative energy columns and take differences; do not read energy from the SOC column." },
  { id:"Q99", chapter:2, type:"multi",
    q:"Which of the following determine which OCV-SOC lookup table is used?",
    opts:["Cell model (e.g. 280Ah, 315Ah)", "Temperature (e.g. 10/25/35/45℃)", "Rest duration", "Current rate at that instant"],
    ans:["A", "B"],
    exp:"Different cell models and temperatures use different tables; rest ≥ 2h is a precondition (not a table axis)." },
  { id:"Q100", chapter:2, type:"multi",
    q:"Which statements about RTE and capacity are correct?",
    opts:["RTE depends on the charge/discharge ratio, not the absolute capacity", "A system can pass RTE but still fail capacity", "Capacity must be checked separately", "Passing RTE automatically means the capacity is fine"],
    ans:["A", "B", "C"],
    exp:"RTE and capacity are independent; both must be verified." },

  /* ---------- Chapter 3: F-STOP Function (Q101-Q150) ---------- */

  { id:"Q101", chapter:3, type:"single",
    q:"In a BESS, F-STOP is best described as:",
    opts:["a SOC calibration function of the BMS", "an emergency-stop interface linking the battery system with external fire-protection / E-stop circuits", "a PCS-level grid-synchronization feature", "a data-logging function for cell voltages"],
    ans:"B",
    exp:"F-STOP is the emergency-stop interface between the BESS and the external fire / E-stop systems. When an emergency occurs outside the battery system, the high-voltage circuit must open immediately and reliably." },

  { id:"Q102", chapter:3, type:"multi",
    q:"Which of the following can trigger an F-STOP (emergency stop)?",
    opts:["Local E-stop button pressed", "Fire-protection system action", "Bank-level F-STOP signal", "Routine SOC calibration"],
    ans:["A", "B", "C"],
    exp:"The three E-stop sources — bank F-STOP, fire protection and the local E-stop button — are wired in series in one loop; any one of them tripping triggers the emergency stop." },

  { id:"Q103", chapter:3, type:"truefalse",
    q:"The fire system, local E-stop button and bank F-STOP are wired in parallel, so at least two of them must trip before an emergency stop occurs.",
    ans:false,
    exp:"They are wired in SERIES: any single one tripping opens the loop and triggers the emergency stop." },

  { id:"Q104", chapter:3, type:"single",
    q:"In normal operation, the F-STOP input dry contact is:",
    opts:["open, and closes on emergency", "pulsing continuously", "closed, and opens on emergency", "in a state that depends on SOC"],
    ans:"C",
    exp:"F-STOP uses normally-closed (NC) design: the loop is closed in normal operation, and OPENING it is the trigger." },

  { id:"Q105", chapter:3, type:"single",
    q:"Why is the F-STOP loop designed so that its contacts are closed during normal operation?",
    opts:["To reduce standby power consumption", "To speed up Modbus communication", "Fail-safe: if a cable breaks or a terminal loosens, the loop opens and the system enters protection instead of silently losing protection", "Because NC contacts are cheaper"],
    ans:"C",
    exp:"Fail-safe (de-energize-to-trip) principle: a broken wire or loose terminal itself opens the loop, so the system goes to the safe state rather than losing its protection capability." },

  { id:"Q106", chapter:3, type:"truefalse",
    q:"If the 24 V control supply is completely lost, the main-circuit contactors remain closed so that the system keeps operating.",
    ans:false,
    exp:"De-energize-to-trip design: losing the 24 V control power de-energizes the relay coils, so the high-voltage contacts necessarily open. This is what makes E-stop the most reliable way to drop the HV circuit." },

  { id:"Q107", chapter:3, type:"single",
    q:"The essence of an E-stop action is:",
    opts:["low-voltage control opens the high-voltage circuit: the control loop de-energizes a relay/contactor coil, whose contacts open the HV path", "the BMS raises an alarm and waits for manual disconnection", "the fuses blow on overcurrent", "the PCS cuts only the AC side"],
    ans:"A",
    exp:"E-stop works by 'low voltage controls high voltage' — cutting the 24 V control loop de-energizes relays whose contacts carry the HV circuit." },

  { id:"Q108", chapter:3, type:"single",
    q:"A 'dry contact' is:",
    opts:["a contact pair that carries no voltage or source of its own — just a switch that opens/closes an external loop", "a contact suitable only for dry environments", "a contact that requires 230 V AC to operate", "a wireless virtual switch"],
    ans:"A",
    exp:"A dry contact is a passive contact pair — the external circuit supplies whatever signal/power flows through it." },

  { id:"Q109", chapter:3, type:"single",
    q:"The F-STOP output dry contact of the BAU is physically implemented as:",
    opts:["the contact of an internal relay that is energized (closed) in normal operation and releases on the highest-level fault", "a 24 V transistor output", "a software flag without any physical contact", "an optocoupler input stage"],
    ans:"A",
    exp:"In normal operation the BMS keeps the internal relay energized (contact closed); on the highest-level (level-3) fault the drive signal is removed and the contact opens. The customer-side F-STOP circuit contains a similar relay." },

  { id:"Q110", chapter:3, type:"single",
    q:"Which contact type of the E-stop button is used in the F-STOP loop?",
    opts:["Normally-open (NO)", "Either one — selectable in software", "Neither — E-stop buttons are wireless", "Normally-closed (NC)"],
    ans:"D",
    exp:"E-stop button backs carry both NO and NC contact blocks; the F-STOP circuit uses the NC pair so that pressing the button (or a broken wire) opens the loop." },

  { id:"Q111", chapter:3, type:"truefalse",
    q:"A fire-protection event can trigger F-STOP automatically, without any person pressing an E-stop button.",
    ans:true,
    exp:"In the fire interlock chain, a fire alarm opens the fire-alarm relay contact, which de-energizes the loop relay and opens the F-STOP input — a fully automatic trigger." },

  { id:"Q112", chapter:3, type:"single",
    q:"When the F-STOP input dry contact opens, the BMS:",
    opts:["opens only the main contactor of the rack that caused the fault", "only raises an alarm and keeps all contactors closed until the EMS confirms", "forces ALL rack main contactors to open, reports the E-stop fault (0x1008 Bit6 = 1), and opens the output dry contact (0x102B Bit0 = 1)", "shuts itself down completely"],
    ans:"C",
    exp:"The safety sequence is: open all rack main contactors → report the E-stop fault and set the status bit → open the output dry contact for external feedback." },

  { id:"Q113", chapter:3, type:"truefalse",
    q:"On F-STOP, only the rack where the fault originated opens its main contactor; the other racks stay closed.",
    ans:false,
    exp:"The command opens the main contactors of ALL racks simultaneously — not only the faulty one." },

  { id:"Q114", chapter:3, type:"single",
    q:"Which Modbus register bit marks the emergency-stop state?",
    opts:["0x1008 Bit6", "0x102B Bit0", "0x1008 Bit0", "0x102B Bit6"],
    ans:"A",
    exp:"0x1008 Bit6 is the emergency-stop status bit, set to 1 (active) when the system has entered E-stop. It can be checked in the Modbus fault table." },

  { id:"Q115", chapter:3, type:"single",
    q:"Which Modbus register bit indicates that the F-STOP output dry contact has opened?",
    opts:["0x1008 Bit0", "0x102B Bit0", "0x1008 Bit6", "0x102B Bit6"],
    ans:"B",
    exp:"0x102B Bit0 = 1 indicates the output dry contact has opened." },

  { id:"Q116", chapter:3, type:"single",
    q:"What is the difference between 0x1008 Bit6 and 0x102B Bit0?",
    opts:["They are two names of the same bit", "0x1008 Bit6 marks that the system has entered E-stop (event/state); 0x102B Bit0 marks that the output dry contact has opened (feedback)", "0x102B Bit0 is only used during charging", "0x1008 Bit6 is written by the EMS and 0x102B Bit0 by the PCS"],
    ans:"B",
    exp:"One is the event state ('system has entered E-stop'), the other is the feedback state ('output contact has opened')." },

  { id:"Q117", chapter:3, type:"single",
    q:"What is the purpose of the F-STOP output dry contact?",
    opts:["to provide a hardwired interlock confirmation to external systems (EMS / fire system / PCS) that the BMS has executed the E-stop — closing the safety loop", "to power the fire-suppression system", "to carry CAN communication", "to measure insulation resistance"],
    ans:"A",
    exp:"The output contact gives external systems a hardwired-level confirmation that the BMS has executed the E-stop, forming a closed safety loop." },

  { id:"Q118", chapter:3, type:"truefalse",
    q:"A 'contactor fail-to-open' fault (the BMS commanded opening but the contactor did not open) also causes the BMS to open the F-STOP output dry contact.",
    ans:true,
    exp:"Besides the input loop opening, a contactor fail-to-open (or other highest-level) fault also opens the output dry contact and sets 0x102B Bit0." },

  { id:"Q119", chapter:3, type:"single",
    q:"On the BAU connector, the F-STOP INPUT dry contact is:",
    opts:["Pin29 / Pin30", "CAN-H / CAN-L", "Pin19 / Pin20", "Pin1 / Pin2"],
    ans:"C",
    exp:"Pin19/Pin20 are the F-STOP input dry contact (sampled by the BAU); Pin29/Pin30 are the output dry contact." },

  { id:"Q120", chapter:3, type:"single",
    q:"On the BAU connector, the F-STOP OUTPUT dry contact is:",
    opts:["Pin19 / Pin20", "Pin1 / Pin2", "CAN-H / CAN-L", "Pin29 / Pin30"],
    ans:"D",
    exp:"Pin29/Pin30 form the output dry contact used to feed the E-stop confirmation back to external systems." },

  { id:"Q121", chapter:3, type:"single",
    q:"Simplified F-STOP control loop: 24 V+ → E-stop button (NC) → interlock nodes in series → BAU output dry contact → loop-relay coil → GND. When the loop-relay coil is energized:",
    opts:["its normally-closed contact opens and a fault is reported", "its normally-open contact closes, Pin19/20 conduct, and no E-stop fault is reported", "the HV main contactor opens", "the system enters sleep mode"],
    ans:"B",
    exp:"Any point in this series chain opening de-energizes the coil → its contact opens → the Pin19/20 loop opens → E-stop. Field troubleshooting means walking this one chain." },

  { id:"Q122", chapter:3, type:"single",
    q:"A relay basically consists of:",
    opts:["a fuse and a varistor", "a coil and contacts: energizing the coil (e.g., 24 V on A1/A2) magnetically closes the contacts", "a battery and an inverter", "a software task and a watchdog timer"],
    ans:"B",
    exp:"Relay = coil + contacts. Apply 24 V to the coil (A1/A2), the coil magnetizes and pulls the contacts closed. Large contactors work the same way." },

  { id:"Q123", chapter:3, type:"truefalse",
    q:"In a BDU, the large screw terminals carry the high-voltage path while the small wires beside them are the 24 V control circuit — the control wires are electrically separate from the HV path.",
    ans:true,
    exp:"'Low voltage controls high voltage': the 24 V control wires drive the contactor coil; the HV current flows through the large terminals. They are independent circuits." },

  { id:"Q124", chapter:3, type:"single",
    q:"The bidirectional interlock between BMS and EMS means:",
    opts:["the BMS controls the EMS unconditionally", "the interlock only works while charging", "if either side triggers F-STOP, both sides open their loops at the same time", "the EMS can monitor but never act"],
    ans:"C",
    exp:"When the BAU detects the input loop open, it sets the register and notifies the EMS; the EMS then also opens its side. Either side tripping causes both to disconnect." },

  { id:"Q125", chapter:3, type:"single",
    q:"Why is a fault-reset button necessary in the F-STOP circuit?",
    opts:["to discharge the DC bus", "to reboot the BMS", "because the input loop opening → E-stop → output contact opening prevents the input loop from closing again (deadlock interlock); after the fault is cleared, reset re-closes the output contact so the loop can recover", "to recalibrate SOC"],
    ans:"C",
    exp:"Without reset, once the output contact opens, the interlock loop can never close again — a dead-loop interlock. After clearing the fault, press reset to restore the output contact and re-close the loop." },

  { id:"Q126", chapter:3, type:"truefalse",
    q:"Relay designations (such as K3/K4) and wire numbers are standardized across all sites, so drawings from one project can be used directly at another site.",
    ans:false,
    exp:"They differ site by site. Always troubleshoot against the as-built drawings of the specific site." },

  { id:"Q127", chapter:3, type:"multi",
    q:"Which of the following can simulate (trigger) an F-STOP on site?",
    opts:["Sending a Modbus command to clear faults", "Pressing the E-stop button", "Power-cycling the EMS", "Switching a rack BDU manual disconnect to OFF"],
    ans:["B", "D"],
    exp:"The manual disconnect's auxiliary contact is wired in series with the F-STOP input loop, so opening the disconnect opens the loop — the simplest way to simulate F-STOP." },

  { id:"Q128", chapter:3, type:"single",
    q:"Why can switching the manual DC disconnect to OFF simulate an F-STOP?",
    opts:["its auxiliary contact is in series with the F-STOP input loop, so opening the switch opens the loop", "it directly cuts the HV bus", "it resets the BAU processor", "it isolates the PCS from the grid"],
    ans:"A",
    exp:"The disconnect's auxiliary contact belongs to the F-STOP input series loop, so its state change has exactly the same effect as tripping the E-stop." },

  { id:"Q129", chapter:3, type:"single",
    q:"The manual DC disconnect may be operated (e.g., for an F-STOP test) only when:",
    opts:["the system is under full load", "at any time, regardless of load", "the system is in a level-2 alarm", "no current is flowing — e.g., grid-connected but with no charge/discharge command in progress"],
    ans:"D",
    exp:"Opening the disconnect while current flows is a load-break operation, which is not allowed. A proper F-STOP test window: after grid connection, before any charge/discharge action." },

  { id:"Q130", chapter:3, type:"truefalse",
    q:"If the main contactor is closed and current is flowing, you may still open the manual disconnect, because the BMS will open the contactor anyway.",
    ans:false,
    exp:"Not allowed — that is load-break switching. The BMS would open the contactor and a level-3 contactor fault could also be triggered." },

  { id:"Q131", chapter:3, type:"single",
    q:"A site keeps reporting an F-STOP fault and cannot connect to the grid. The FIRST thing to check is:",
    opts:["whether every rack's manual disconnect is in the ON position", "replace the BAU", "re-flash the BMS firmware", "replace all racks"],
    ans:"A",
    exp:"With many racks on site, one or two disconnects left open keep the series F-STOP loop open and block grid connection. Rule them out first — the cheapest check and the most common cause." },

  { id:"Q132", chapter:3, type:"single",
    q:"The ABA substitution test for the BAU is performed as follows:",
    opts:["swap in any spare BAU and see whether communication improves", "swap in a known-good, correctly configured BAU: fault persists → the original BAU is fine and the problem is in the external loop; fault disappears → the original BAU is faulty (reinstall it to confirm)", "compare the BAU serial numbers", "measure only the BAU supply voltage"],
    ans:"B",
    exp:"ABA testing first draws the boundary: BAU itself vs external loop. If the fault disappears with the substitute, reinstall the original to confirm the fault reappears before concluding." },

  { id:"Q133", chapter:3, type:"single",
    q:"The F-STOP fault tree first splits into two main branches:",
    opts:["AC-side and DC-side faults", "hardware and software faults", "BMS and PCS faults", "BAU unit fault and signal-loop (wiring) fault"],
    ans:"D",
    exp:"First decide whether the BAU itself is OK (ABA test), then walk the external signal loop segment by segment." },

  { id:"Q134", chapter:3, type:"single",
    q:"The correct order of the F-STOP signal chain to inspect is:",
    opts:["BAU connector → terminal block → contactor auxiliary contact", "contactor → PCS → grid", "EMS → cloud → BMS", "terminal block → fire system → BAU"],
    ans:"A",
    exp:"Build the full loop from the BAU circuit drawing plus the customer-side installation drawing, then check it segment by segment: BAU side → terminals → contactor auxiliary contacts." },

  { id:"Q135", chapter:3, type:"multi",
    q:"The two basic checks when troubleshooting the F-STOP signal loop are:",
    opts:["check that each wire sits in the correct position (against the drawings)", "check loop continuity with a multimeter", "perform a full battery capacity test", "check the PCS firmware version"],
    ans:["A", "B"],
    exp:"Check A (correct positions, visual, against drawings) and check B (continuity, multimeter beep mode) — nothing more is needed for a dry-contact loop." },

  { id:"Q136", chapter:3, type:"truefalse",
    q:"Before measuring continuity with a multimeter, first verify visually that each wire sits in the correct position according to the drawings.",
    ans:true,
    exp:"Wrong position is the simplest fault class and must be ruled out first; continuity readings are meaningless if the wire is in the wrong terminal." },

  { id:"Q137", chapter:3, type:"single",
    q:"The 'short-bypass' method for locating a fault in a dry-contact loop:",
    opts:["short the two wires of the suspect component: if the fault disappears, the component is healthy", "short the two wires of the suspect component: if the fault disappears, that component is the problem", "always eliminates the fault permanently", "is forbidden in all cases"],
    ans:"B",
    exp:"Bypass the suspect device and see whether the fault follows it: if shorting it clears the fault, the device (not the rest of the loop) is faulty." },

  { id:"Q138", chapter:3, type:"single",
    q:"Shorting the contactor's auxiliary-contact wires clears the F-STOP warning. What does this mean and what is the next step?",
    opts:["the wiring is faulty — re-crimp all terminals", "the BAU is faulty — replace it", "the contactor (auxiliary contact) is faulty — notify the customer to check/replace it, since the contactor is customer-side equipment", "nothing — it will self-recover"],
    ans:"C",
    exp:"The fault follows the bypassed component, so the contactor is faulty. It belongs to the customer side, so the customer is notified to check or replace it." },

  { id:"Q139", chapter:3, type:"single",
    q:"Which multimeter function is the core tool for F-STOP loop checks?",
    opts:["capacitance mode", "continuity (beep) mode", "frequency mode", "temperature mode"],
    ans:"B",
    exp:"The multimeter is mainly used in continuity (beep) mode to check whether each segment of the dry-contact loop conducts." },

  { id:"Q140", chapter:3, type:"truefalse",
    q:"Even with every wire intact, a poorly crimped or loose terminal can keep the F-STOP loop open and the warning active.",
    ans:true,
    exp:"Terminals are nodes of the series loop: bad crimping or looseness opens the loop just like a broken wire. Measure continuity across each terminal to confirm." },

  { id:"Q141", chapter:3, type:"multi",
    q:"Useful tools for F-STOP troubleshooting include:",
    opts:["a laptop with the BMS host-PC software", "a multimeter", "a CAN adapter for BMS-to-PC communication", "a battery capacity tester"],
    ans:["A", "B", "C"],
    exp:"The standard kit: laptop with host software (monitor/controls the battery system), multimeter (beep mode), and a CAN adapter plus communication harness between the BMS and the PC." },

  { id:"Q142", chapter:3, type:"single",
    q:"The field three-step method when the F-STOP loop relay is not picked up:",
    opts:["1) replace the relay → 2) replace the BAU → 3) replace the racks", "1) check whether the relay is picked up (status LED) → 2) check whether its coil gets 24 V → 3) walk the loop for opens (E-stop pressed? NC contact wired correctly? output contact opened by a BMS fault? broken wire?)", "1) measure cell voltages → 2) restart the EMS → 3) reboot everything", "in random order, whichever is fastest"],
    ans:"B",
    exp:"Three steps: relay state (LED) → coil supply (24 V at A1/A2) → walk the series loop for the open point." },

  { id:"Q143", chapter:3, type:"truefalse",
    q:"The exact conditions under which the customer side (fire / E-stop system) opens its contact are always documented in the battery manufacturer's manual.",
    ans:false,
    exp:"Customer-side trigger conditions are outside the battery manufacturer's scope and must be confirmed with the customer on site — part of the checklist when an F-STOP warning will not clear." },

  { id:"Q144", chapter:3, type:"single",
    q:"A large rack-to-rack voltage difference causes:",
    opts:["only a slight efficiency drop", "only communication errors", "no consequence at all", "inability to connect to the grid — and even after the voltages are pulled level, the capacity gap of the weaker cells remains, reducing usable capacity"],
    ans:"D",
    exp:"Two consequences: the HV connection (grid connection) is blocked, and even if the voltages are later equalized, the capacity deficit of the weak cells remains, so usable capacity is still reduced." },

  { id:"Q145", chapter:3, type:"single",
    q:"Circulating current between racks connected to the same DC bus:",
    opts:["flows from the higher-voltage rack into the lower-voltage rack; total capacity is unchanged (the racks average out) and it stops once their states match", "permanently destroys the BMS", "is caused by CAN communication", "only appears during grid faults"],
    ans:"A",
    exp:"Rack-to-rack circulation transfers charge between racks without dissipating it — total capacity is preserved; it decays to zero once the two racks' states match." },

  { id:"Q146", chapter:3, type:"truefalse",
    q:"Passive balancing increases the total capacity of a pack.",
    ans:false,
    exp:"In passive balancing, cells other than the lowest discharge through resistors, so the energy is dissipated as heat — total capacity DECREASES. This differs from rack-to-rack circulation, which preserves total capacity." },

  { id:"Q147", chapter:3, type:"truefalse",
    q:"Passive-balancing trigger conditions are AND-related: balancing starts only when ALL conditions are satisfied simultaneously.",
    ans:true,
    exp:"Each method requires every condition to hold at the same time (e.g., voltage above a threshold AND cell delta above a threshold); missing any single one blocks the trigger." },

  { id:"Q148", chapter:3, type:"single",
    q:"The passive-balancing decision is based on:",
    opts:["the difference between displayed SOC and inner SOC", "the EMS-reported SOC", "the PCS-reported SOC", "the inter-cell difference of the inner SOC (estimated from the cells' static voltage via the OCV table) — not the displayed SOC"],
    ans:"D",
    exp:"Displayed SOC and inner SOC can differ widely without triggering balancing; the criterion is the true (inner, OCV-table-based) SOC difference between cells." },

  { id:"Q149", chapter:3, type:"truefalse",
    q:"During passive balancing, the lowest cell also discharges through its balancing resistor.",
    ans:false,
    exp:"The lowest cell does NOT participate in balancing; the other cells discharge through their resistors to align toward it." },

  { id:"Q150", chapter:3, type:"single",
    q:"During passive balancing, the lowest cell keeps dropping with a slope clearly steeper than the other (linear, overlapping) cells. This indicates:",
    opts:["excessive self-discharge or a micro-short in that cell", "normal balancing behaviour", "an open balancing resistor", "a communication error"],
    ans:"A",
    exp:"The lowest cell is excluded from balancing, so if it still drops faster than the others it likely has excessive self-discharge or a micro-short. Verify by disabling balancing and watching whether it keeps dropping; if so, schedule replacement." }

];
